### ISSUE TITLE
[Bug] lag on some pages?

### ISSUE THREAD

**Issue by tmpm697** [searchmarkers/mark-my-search#124]
info:
```
chromium --version: Chromium 114.0.5735.45 Arch Linux
mark my search: 1.13.7 -- latest
os: linux
```

steps to produce:
```
1. open new tab and type in address bar: aws_network_acl resource terraform
2. click on first page, should be like [this](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/network_acl)
3. observe page long loading to display content, chromium sometime gives box asking to continue waiting for kill the tab --> tab not responding
```
note that the above issue happen sometime in busy work with multiple tab or randomly that i don't know, but it happens quite often for me.

i tried to find an option in settings to disable mark my search on a certain but not found or an option to not inherit search to a cerntain page.

**Comment by ator-dev** [comment]
Thanks for the report!

I can reproduce this in all browsers when a specific option is OFF. If I keep "CLASSIC" highlighting on, the page loads quickly. Could you check whether or not you have it enabled please? 

![image](https://github.com/searchmarkers/mark-my-search/assets/66553618/42ae9691-20a6-40cc-8dc4-1d20b9bd308f)

I will do some more diagnosis, but it may take a while to release a fix, due to student work.

**Comment by tmpm697** [comment]
Yes, I used the `experimental APIs` option as it's critical to display searches with different colors.

**Comment by ator-dev** [comment]
I'm confused - do you mean the "Visibility when highlighting search engine keywords" options *should* be enabled by default?

"Highlights begin visible" means that if started from a search, highlights do not display at first (you can use the eye button or a shortcut to turn them on).

"Highlights are always visible on search pages" means that regardless of the above setting, highlights are *always* displayed on search pages.

**Comment by tmpm697** [comment]
I meant this `"Highlights are always visible on search pages" means that regardless of the above setting, highlights are always displayed on search pages.`

Reading two options give a bit confuse, but I want it default just to highlight different colors right a way when using without toggle option in settings --> this can be most wanted if new users start using this plugin I assume.

**Comment by tmpm697** [comment]
just checked, enable `Highlights begin visible` is enough and it seem it's enabled by default, don't know why last my last check I lose colors for a while and need to check both options. 

Anyway it's good now, thanks for help.

**Comment by ator-dev** [comment]
Strange, thanks for verifying. I'll keep an eye on it (:

Since you mentioned the options being confusing, here's a preview of the new options page I am building. It's planned to release with support for better storage defaults and clearer options with tooltips.

![image](https://github.com/searchmarkers/mark-my-search/assets/66553618/92ac1def-3cc5-46a2-80f6-563a1830f6e5)

By the way, please consider writing a review if you enjoy MMS. It has taken a lot of work and it will always be free. A positive review will help others to discover it.

Thank you for the help :slightly_smiling_face:
