### ISSUE TITLE
QOL Suggestions

### ISSUE THREAD

**Issue by rokville** [searchmarkers/mark-my-search#136]
Here are a couple of thoughts, but I think they are related enough to keep them in a single post.

1. A setting to keep the overlay toolbar always on and available
  - I'd like an option to keep the (collapsed) toolbar always available (ideally as that little sideways carrot) so if I want to quickly search the page (e.g., adding new terms - a new find request - no previous highlighting exists) - I can do it quickly, right on the page I'm reviewing.  If there is a hotkey for this, I don't see it, but ideally it would be a setting in and of itself.

2. Hotkey(s) to replace CTRL+F
  -  Ideally, I would replace or substitute the use of CTRL+F (CMD+F) with a similar function that uses this shortcut. This plugin is ideal for "finding" in the page (especially for multiple terms), but muscle memory has me expecting a hotkey to execute the find, but I don't want FIREFOX's find, I want yours!
  - Maybe there are other hotkey ideas are out there (e.g., toggle highlighting)

3. Facilitate deleting "find terms" in the toolbar
  - maybe just adding an "x" next to the edit button?  
  - I like that, when you click edit (pencil icon), the cursor is moved the the field and the term is highlighted.  
  - That's great for editing, but to delete you either have to 
    - Click edit, move your mouse a variable distance (depending on the search term's length) to hit the trashcan
    or
    - Click edit, press delete key on keyboard, press enter on the keyboard, press escape on the keyboard, click back into the page.

**Comment by ator-dev** [comment]
Hi, thank you for the suggestions! You might have noticed a lapse of activity on this repo, and it's not because I'm not interested in continuing development, but because I burnt myself out and am taking a break to do some more creative things. However, I am certainly going to pick this up again - hopefully soon (:

1: Sure, this wouldn't be a problem. As of reviewing this, I realised that when the toolbar is "collapsed", you have to press the button or the configured shortcut to begin entering terms. A good QOL improvement would be expanding it automatically when you press Alt+. (to focus the + button).

2: This should be available already, as Alt+M by default. It activates the add-on on the current page, with the + button focused. Is this what you're asking for?

![image](https://github.com/searchmarkers/mark-my-search/assets/66553618/81717522-867a-4376-a7dd-309eeec0f430)

![image](https://github.com/searchmarkers/mark-my-search/assets/66553618/3cc487c3-0288-4b2a-984c-4e875f832f9e)

3:
- I *could* add an option for this. There is already a (non-obvious) way at the moment though. You can right-click the edit button to immediately delete the keyword. MMS should probably introduce interested users to this feature, perhaps in an optional tutorial.
- Note that it is possible to do this entirely with the keyboard, although it's a bit long. You can focus the + button (with Alt+. by default) and then Shift+Tab (or left-arrow) backwards through the keywords. As you describe, you can delete the text, and then either tab all the out of the bar, or press Enter and then Escape.

**Comment by rokville** [comment]
Thank you for your reply and your hard work on this plugin.  I did see you were taking a break and I hope you take all the time you need!

1. Thanks for considering it.  Knowing about *ALT+M* will help with this for now.
2. Thank you for pointing out *ALT+M*, that's exactly what I wanted.  My apologies if that's noted somewhere obvious and I missed it.  
3. That *right click trick* is great to address my personal pain point and agree that an introduction would be helpful.  honestly, I use this plugin all the time and I don't really know how to use the modal that pops down from the plugin icon.

**Comment by ator-dev** [comment]
No worries, I'm glad it's useful for you! Happy to help with regard to suggestions.

You may have originally installed an older version of the extension; these days MMS shows a helpful message about the shortcut to use on the startpage. No worries if you missed it though.

![image](https://github.com/searchmarkers/mark-my-search/assets/66553618/f4799d6c-0c75-40a9-b434-102b5fb7981f)

The popup modal is far from essential, but it contains two useful settings and some quick links (as well as advanced functionality: site filtering and auto-inserting keywords). Everything's getting a visual refresh and more customisation, when I get around to finishing the update (:

**Comment by ator-dev** [comment]
Since your problems were addressed, I'm closing as completed, with the expectation that accessibility of features will be improved. I am happy to reopen it if someone is interested in the additional setting. Let me know if that's you :slightly_smiling_face:
