### ISSUE TITLE
[Feature request] Quick intro text / animation

### ISSUE THREAD

**Issue by vatterspun** [searchmarkers/mark-my-search#2]
I had the add-on downloaded and running for a while before I realized how it worked.  I finally just entered something in on DuckDuckGo and finally saw how it works.  I was then further pleased to see it worked on almost ever site search I use.

Recommend at launch having something that specifically spells this out or offers some animation maybe on the home page to this effect?  If I get some bandwidth, I'll put something together to show what I'm thinking.

**Comment by ator-dev** [comment]
I wondered if this would be a problem, and you're right that the addon isn't that intuitive at the moment. Perhaps when you do your first search or first few searches, animations play to showcase some of the features as you're on the page? As you suggest a launch page or animation would also be good as an introduction.

The least discoverable features right now are probably editing/deleting a 'search term' (right-click on the button and change the text), and changing the 'matching mode' of one (pull down from the button and release over an option, i.e. hold left click and move the mouse away); neither of which are exactly obvious.

**Comment by vatterspun** [comment]
> Perhaps when you do your first search or first few searches, animations play to showcase some of the features as you're on the page?

That would be great.  I'll see if I can't model something in the next month or two.  Free time at the moment is low.

**Comment by ator-dev** [comment]
Thank you for offering to help, and sorry again for my late response - I really appreciate it. There's no pressure at all to commit to it of course, I don't mind at all if you decide not to or can't.

_Note: if you do try modelling something and want to include branding, the final icon won't be the current "magnifying glass with highlighting" (which makes poor use of space and looks unclear). I'm thinking of "map with markers" at the moment, but any map theming would work regardless._

**Comment by ator-dev** [comment]
I have finally implemented an onboarding page for v1.8.0, which is displayed only when you install the extension. This is how it currently looks:

![image](https://user-images.githubusercontent.com/66553618/197891050-2a4a6954-6f74-4164-8262-28c06a312f72.png)

_Note that a second tab is used to document more of the extension without overwhelming the user._

There is also a separate page for users who have just uninstalled the extension, which due to particular requirements has been added as part of a GitHub Pages site.

I'm very happy with this design, particularly since it has allowed me to reuse the generation system I built for the popup (although the uninstalled page is currently being manually updated by copying and tweaking generated JavaScript files). **Feel free to reopen this issue** - I'm open to new ideas for improving or adding to this experience.
