### ISSUE TITLE
Bug: Form search deletes search words (issue with BBCode sites)

### ISSUE THREAD

**Issue by vatterspun** [searchmarkers/mark-my-search#68]
The way I found this was on a BBCode site.  I'm not sure how common this issue is and because the workaround is so simple, it might well be low priority.  I was just proud I found a bug.

SETUP: Firefox 107.0

STEPS:

1. Login to a given BBCode website search
2. Reply to one of the posts and use a word that's in your (still visible) search view
3. Preview the post

DEFECT:

Deletes word from form.  If you click Preview again, the world will be removed from the resulting post.

SCREENSHOT

![image](https://user-images.githubusercontent.com/1289134/203365046-d388091a-e135-46b0-9a60-51a0ad99d4d3.png)

WORKAROUND

Just close the search view (press X)

**Comment by ator-dev** [comment]
Thanks for letting me know, and well done for finding and testing a bug. This is definitely related to a fundamental issue with 'search highlighter' extensions, including MMS: it works by essentially breaking apart bits of text inside webpages to insert highlight tags, so any webpage script which requires the structure to be exactly as expected will probably break something.

Unfortunately this even happens on DuckDuckGo - hovering over or focusing a result makes the URL look mixed up if it was highlighted. There's another site I know of which looks vile after highlighting, because the highlight elements end up inserted into code previews. The good news is I'm working on a new algorithm based on the brand new ['Houdini' paint APIs](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Painting_API), which works without changing any elements - you can see my progress [in this branch](https://github.com/ator-dev/mark-my-search/tree/paint), but sadly it will take some time for Firefox to implement the APIs.

Could you link the website domain please? I can't find one that does this, and would be interested to know how it's happening to what looks like a <textarea>.

**Comment by vatterspun** [comment]
> Could you link the website domain please? I can't find one that does this, and would be interested to know how it's happening to what looks like a <textarea>.

Sent an email to the one listed on your main page.

**Comment by ator-dev** [comment]
I have now tested it myself, and discovered that adding text inside a <textarea> element is a valid way to set its default value - this is the method used by the website you linked. Mark My Search was then finding this text and adding an element, causing it not to be processed.

I have added <textarea> to the blocked elements for 1.10.3 and confirmed that this fixes the problem. There is no disadvantage since highlighting is ignored for them anyway. Thanks for the report!

**Comment by ator-dev** [comment]
Following up on my comment about how Mark My Search operates (breaking apart websites): Progress on the "paint" branch is now nearing completion. Progress and information can be viewed in #71, which will be merged once acceptably stable.

Performance gains range from mediocre to vast, and essentially make Mark My Search usable even for tasks such as highlighting the letters of the alphabet. As far as I know no other search highlighter is capable of this, and certainly none can highlight webpages with no damage or data loss.

Needless to say, I am very happy with this progress and will probably make a product hunt announcement to raise awareness (:
